[project]
name = "store-bot-web"

[services.store-bot-web]
startCommand = "python -m bot.main"
envVars = ["BOT_TOKEN","ADMIN_IDS","EXCHANGE_RATE","TZ","CURRENCY"]

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
